// 文件路徑: src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GoogleTranslateWidget from "@/components/GoogleTranslateWidget";
import Header from "@/components/Header";

import { createClient } from '@/utils/supabase/server';
import { cookies } from 'next/headers';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * 廣告橫幅組件 (已補完內部實現)
 * 這個組件會將橫幅固定在頁面底部。
 */
const PromoBanner = ({ banner }: { banner: { url: string; name: string | null } | null }) => {
  // 如果沒有傳入 banner 數據，或者 banner 沒有 url，則不渲染任何內容
  if (!banner || !banner.url) {
    return null;
  }

  return (
    // 使用 fixed positioning 將橫幅固定在視窗底部
    // h-28 md:h-32 的高度對應 body 上的 pb-28 md:pb-32 padding
<div className="fixed bottom-0 left-1/2 -translate-x-1/2 w-full max-w-[1200px] z-50 p-[10px]">
  <div className="relative aspect-[1200/200]">
<Image
        src={banner.url}
        alt={banner.name || "Promotional Banner"}
        fill={true} 
        style={{ objectFit: "cover"  }}
        className="card"
        priority
      />
    </div>
    </div>

  );
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const supabase = createClient(cookieStore);

  const { data: { user } } = await supabase.auth.getUser();

  let profile = null;
  if (user) {
    const { data: userProfile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
    profile = userProfile;
  }
  
  // 這段 Promise.all 已經在獲取您需要的 'promo_banner'
  const [
    { data: activeBanner },
    { data: logoData }
  ] = await Promise.all([
    supabase.from('img_admin').select('url, name').eq('asset_type', 'promo_banner').eq('is_active', true).single(),
    supabase.from('img_admin').select('url').eq('asset_type', 'logo').eq('is_active', true).single()
  ]);

  const logoUrl = logoData?.url || null;

  return (
    <html lang="en">
      {/* body 上的 padding-bottom 是為了防止主要內容被底部的 fixed banner 遮擋 */}
      <body className={`${inter.className} pb-28 md:pb-32 `}>
        <GoogleTranslateWidget />
        
        <Header user={user} profile={profile} logoUrl={logoUrl} />
        
        <main>
          {children}
          
        </main>
        
        {/* 在這裡渲染橫幅組件，並傳入從 Supabase 獲取的數據 */}
        
        <PromoBanner banner={activeBanner} />
        
      </body>
    </html>
  );
}