// 文件路徑: src/app/layout.tsx (最終修復版)

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GoogleTranslateWidget from "@/components/GoogleTranslateWidget";
import Header from "@/components/Header";

import { createClient } from '@/utils/supabase/server';
import { cookies } from 'next/headers';
import Image from 'next/image';
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 廣告橫幅組件 (保持不變)
const PromoBanner = ({ banner }: { banner: { url: string; name: string | null } | null }) => {
  if (!banner) return null;
  // ... (此組件內部代碼保持不變)
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const supabase = createClient(cookieStore);

  const { data: { user } } = await supabase.auth.getUser();

  let profile = null;
  if (user) {
    const { data: userProfile } = await supabase.from('profiles').select('role').eq('id', user.id).single();
    profile = userProfile;
  }
  
  const [
    { data: activeBanner },
    { data: logoData }
  ] = await Promise.all([
    supabase.from('img_admin').select('url, name').eq('asset_type', 'promo_banner').eq('is_active', true).single(),
    supabase.from('img_admin').select('url').eq('asset_type', 'logo').eq('is_active', true).single()
  ]);

  const logoUrl = logoData?.url || null;

  return (
    <html lang="en">
      <body className={`${inter.className} pb-28 md:pb-32`}>
        <GoogleTranslateWidget />
        
        {/* 【核心修復】: 將獲取到的 user 和 profile 都作為 props 傳遞給 Header 組件 */}
        <Header user={user} profile={profile} logoUrl={logoUrl} />
        
        <main>
          {children}
        </main>
        
        <PromoBanner banner={activeBanner} />
      </body>
    </html>
  );
}